The new ES6 based Awesome books
Sami-Ullah-Tufail/Awesome-books-ES6 pull request #1
Opened 2023-08-16 22:04 UTC by Sami-Ullah-Tufail

## ES6 Awesome Books 
Use of ES6 modules
Use of import and export functionality
Use of Local Storage

2023-08-16 22:52 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @Sami-Ullah-Tufail, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-16 22:52 UTC, anagudelogu commented on Modules/books.js
> +/* eslint-disable */
- [ ] Please avoid disabling linters as they are very useful to keep a consistent code format and ensure the use of best practices. Instead, please consider solving the errors! 🤓 🔧

2023-08-16 22:52 UTC, anagudelogu commented on Modules/books.js
> +    // console.log(books,newbook);
- [ ] Please don't forget to remove old pieces of commented code, they make your code base look ugly and make it less readable. 🤓 🔧

2023-08-16 22:52 UTC, anagudelogu commented on Modules/nav.js
> +// contact.addEventListener('click', () => showsection('contactSection'));
- [ ] Please don't forget to remove old pieces of commented code, they make your code base look ugly and make it less readable. 🤓 🔧

2023-08-16 22:52 UTC, anagudelogu commented on Modules/books.js
> +    book_storage.appendChild(removeButton);
- [ ] Testing your app, I found that adding a book isn't working:

[Screencast from 16-08-23 17:49:26.webm](https://github.com/Sami-Ullah-Tufail/Awesome-books-ES6/assets/77069011/00aa3071-3d44-41b4-a0df-f4eead362847)

Also, there's an error in the console about this `book_storage` variable. Please consider fixing this! 🤓 🔧

2023-08-16 22:52 UTC, anagudelogu commented on index.js
> +document.addEventListener('DOMContentLoaded', initializeApp);
- [ ] There's a missing requirement in this milestone:

![image](https://github.com/Sami-Ullah-Tufail/Awesome-books-ES6/assets/77069011/a5d80ed1-7663-4429-a7d6-9e9d7af6c3cf)

Please consider implementing it! 🤓 🔧

2023-08-17 14:10 UTC, Olamarx approved these changes
Hi @Sami-Ullah-Tufail,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media1.giphy.com/media/3oz8xAFtqoOUUrsh7W/giphy.gif"/>
## Highlights
- All changes fixed ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-18 22:07 UTC, merged